# Generated by Django 3.2 on 2022-09-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='quantity',
        ),
    ]
